version: '3'
services:
  web:
    image: nginx.demo
    volumes:
      - ./www/:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
      - db
  php:
    image: php:7.1.11-fpm-alpine
    volumes:
      - ./www/:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
  db:
    image: mariadb:10.2.10
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
