version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    container_name: front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./www:/var/www
      - ./app:/var/app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  
  api: 
    image: nginx:1.15-alpine
    container_name: api
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    networks:
      - backend

networks:
  frontend:
  backend: